- name: Install SAP HANA
  hosts: all
  become: yes

  vars:
              #####################################################
              # Default Subscription Information for HANA Servers
              # used in: mk-ansible-roles.rhn-subscribe

              satellite_server: satellite.example.com
              reg_activation_key: sap-hana
              reg_organization_id: RHPDS_Demo
              reg_server_insecure: yes

              reg_osrelease: 7.4
              repo_reset: true
              repositories:
                 - rhel-7-server-e4s-rpms
                 - rhel-sap-hana-for-rhel-7-server-e4s-rpms

              ####################################################
              # Default Timeserver settings
              # used in: rhel-system-roles.timeserver

              ntp_servers:
                      - hostname: 0.rhel.pool.ntp.org
                        iburst: yes
                      - hostname: 1.rhel.pool.ntp.org
                        iburst: yes
                      - hostname: 2.rhel.pool.ntp.org
                        iburst: yes
                      - hostname: 3.rhel.pool.ntp.org
                        iburst: yes

              # SAP Precoonfigure role
              # SAP-Media Check
              install_nfs: "tower.example.com:/export"
              installroot: /install/hxe
              installversion: "HANA_EXPRESS_20"
              hana_installdir: "{{ installroot + '/' + installversion }}"

              hana_pw_hostagent_ssl: "MyS3cret!"
              id_user_sapadm: "30200"
              id_group_shm: "30220"
              id_group_sapsys: "30200"
              pw_user_sapadm_clear: "MyS3cret!"

 roles:
              - { role: mk-ansible-roles.subscribe-rhn }
              - { role: linux-system-roles.timesync }
              - { role: mk-ansible-roles.disk-init }
              - { role: mk-ansible-roles.saphana-preconfigure }
              - { role: mk-ansible-roles.saphana-deploy }
