- name: Install SAP HANA
  hosts: all
  become: yes

  
  roles:
              - { role: mk-ansible-roles.subscribe-rhn }
              - { role: linux-system-roles.timesync }
              - { role: mk-ansible-roles.disk-init }
              - { role: mk-ansible-roles.saphana-preconfigure }
              - { role: mk-ansible-roles.saphana-deploy }
